IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

MODELS = {
    "EFFICIENTNET_B3": "efficientnet_b3",
    "RESNET18": "resnet18",
    "RESNET50": "resnet50",
}
DEFAULT_MODEL_NAME = MODELS["EFFICIENTNET_B3"]

POSITIVE_CLASS_NAME = "PNEUMONIA"

# 必須字母排序，索引要與權重一致
CLASS_NAMES = ["NORMAL", "PNEUMONIA"]
if CLASS_NAMES != sorted(CLASS_NAMES):
    raise ValueError(f"CLASS_NAMES 必須是字母排序: {CLASS_NAMES}")

# 切分種子刻意與訓練種子分開
DEFAULT_SPLIT_SEED = 42
